### ISSUE TITLE
Consolidating similar variant calls

### ISSUE THREAD

**Issue by ashamehta** [HudsonAlpha/UDN_SV_export#1]
Hi, I'm trying to consolidate similar variant calls in the UDN dataset using SURVIVOR merge. This method requires that I split the multisample vcf into individual sample files first, though. Would it be possible to release this data with IDs to group variant calls by sample? 

Alternatively, please let me know if you have a suggestion for a better way to accomplish this. 

Thanks in advance for your help and for releasing this data!

**Comment by holtjma** [comment]
Hi,

Unfortunately, I'm not actually authorized to release patient level data publicly (we were allowed to do it in aggregate as we did here).  It might be possible to get that information, but it would require talking to the UDN coordinating site and likely working out some agreement with them.

**Comment by ashamehta** [comment]
Got it, that makes sense. Thank you for your quick response!
